import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import SessionProviderWrapper from "./components/SessionProviderWrapper";
import ClientLayoutWrapper from "./components/ClientLayoutWrapper";
// import { usePathname } from "next/navigation";
// import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Safa Art Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // current path বের করি

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProviderWrapper>
          <ClientLayoutWrapper>{children}</ClientLayoutWrapper>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
